# Generated by Django 3.1.2 on 2020-10-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_builder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crops',
            new_name='Crop',
        ),
    ]
